export const COMPLETE = 'COMPLETE'
export const IN_PROGRESS = 'IN_PROGRESS'
export const PENDING = 'PENDING'

const dataSource = [
  {
    key: 'Weekly Stocktip',
    status: IN_PROGRESS,
    assetType: 'Stocks',
    strategy: 'Value investing',
    price: '$29/w',
    website: 'https://weeklystocktip.com',
    winRate: 93.67,
    averageReturn: 94.85,
    holdingPeriod: '408 days',
    score: 96,
    risk: 'low',
    effort: 'low',
    reviewLink: '/reviews/weeklystocktip',
  },
  {
    key: 'Options Strategies Insider',
    status: IN_PROGRESS,
    assetType: 'Options',
    strategy: null,
    price: '$97/m',
    website: 'https://optionstrategiesinsider.com',
    winRate: 90,
    averageReturn: 49.5,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/options_strategies_insider',
  },
  {
    key: 'I know first',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: undefined,
    website: 'https://iknowfirst.com',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/iknowfirst',
  },
  {
    key: 'Algo Trader',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: undefined,
    website: 'https://www.algotrader.com/',
    winRate: 54,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/algotrader',
  },
  {
    key: 'Tai Lopez: Hidden Signals',
    status: PENDING,
    assetType: 'Stocks & Crypto',
    strategy: undefined,
    price: undefined,
    website: 'https://www.hiddensignals.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/hidden_signals',
  },
  {
    key: 'Ablesys',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: undefined,
    website: 'https://www.wintick.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/able_sys',
  },
  {
    key: 'ATT Signals',
    status: PENDING,
    assetType: 'Stocks & Forex',
    strategy: 'Swing & Trend trading',
    price: undefined,
    website: 'https://www.att-signals.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: 'weeks',
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/att_signals',
  },
  {
    key: 'Stock Spotter',
    status: PENDING,
    assetType: 'Stocks',
    strategy: 'Swing trading',
    price: undefined,
    website: 'http://www.stockspotter.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: '1 week',
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/stock_spotter',
  },
  {
    key: 'Hedgefund Z',
    status: PENDING,
    assetType: 'Stocks',
    strategy: null,
    price: '$49/m',
    website: 'https://www.hedgefund-z.com/',
    winRate: null,
    averageReturn: null,
    holdingPeriod: null,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/hedgefund_z',
  },
  {
    key: 'Market Trend Signal',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: undefined,
    website: 'https://www.markettrendsignal.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: undefined,
    effort: undefined,
    reviewLink: '/reviews/hedgefund_z',
  },
]

export default dataSource
