export const COMPLETE = 'COMPLETE'
export const IN_PROGRESS = 'IN_PROGRESS'
export const PENDING = 'PENDING'
export const SCAM = 'SCAM'
export const UNKNOWN = 'UNKNOWN'
export const UNDISCLOSED = 'UNDISCLOSED'

const dataSource = [
  {
    key: 'Weekly Stocktip',
    status: COMPLETE,
    assetType: 'Stocks',
    strategy: 'Value investing',
    price: '$29 weekly',
    website: 'https://weeklystocktip.com',
    winRate: 93.67,
    averageReturn: 94.85,
    holdingPeriod: '408 days',
    score: 96,
    risk: 'very low',
    effort: 'very low',
    reviewLink: '/reviews/weeklystocktip',
  },
  {
    key: 'Options Strategies Insider',
    status: IN_PROGRESS,
    assetType: 'Options',
    strategy: UNDISCLOSED,
    price: '$97 monthly',
    website: 'https://optionstrategiesinsider.com',
    winRate: 90,
    averageReturn: 49.5,
    holdingPeriod: undefined,
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/options_strategies_insider',
  },
  {
    key: 'I know first',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: '$189 monthly',
    website: 'https://iknowfirst.com',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/iknowfirst',
  },
  {
    key: 'Algo Trades',
    status: PENDING,
    assetType: 'Stocks',
    strategy: undefined,
    price: '$249 quarterly',
    website: 'https://www.algotrades.net/',
    winRate: 54,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/algotrader',
  },
  {
    key: 'Tai Lopez: Hidden Signals',
    status: PENDING,
    assetType: 'Stocks & Crypto',
    strategy: UNDISCLOSED,
    price: '$197 yearly',
    website: 'https://www.hiddensignals.com/',
    winRate: UNDISCLOSED,
    averageReturn: UNDISCLOSED,
    holdingPeriod: UNDISCLOSED,
    score: UNDISCLOSED,
    risk: UNKNOWN,
    effort: 'very low',
    reviewLink: '/reviews/hidden_signals',
  },
  {
    key: 'Ablesys',
    status: PENDING,
    assetType: 'Stocks',
    strategy: 'Trend trading',
    price: '$3,295 yearly',
    website: 'https://www.wintick.com/',
    winRate: UNDISCLOSED,
    averageReturn: UNDISCLOSED,
    holdingPeriod: '< 1 day',
    score: undefined,
    risk: UNKNOWN,
    effort: 'high',
    reviewLink: '/reviews/able_sys',
  },
  {
    key: 'ATT Signals',
    status: PENDING,
    assetType: 'Stocks & Forex',
    strategy: 'Swing & Trend trading',
    price: '€29.99 monthly',
    website: 'https://www.att-signals.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: 'weeks',
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/att_signals',
  },
  {
    key: 'Stock Spotter',
    status: PENDING,
    assetType: 'Stocks',
    strategy: 'Swing trading',
    price: '$50 monthly',
    website: 'http://www.stockspotter.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: '1 week',
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/stock_spotter',
  },
  {
    key: 'Hedgefund Z',
    status: PENDING,
    assetType: 'Stocks',
    strategy: UNDISCLOSED,
    price: '$49 monthly',
    website: 'https://www.hedgefund-z.com/',
    winRate: UNDISCLOSED,
    averageReturn: UNDISCLOSED,
    holdingPeriod: UNDISCLOSED,
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/hedgefund_z',
  },
  {
    key: 'Market Trend Signal',
    status: PENDING,
    assetType: 'Stocks',
    strategy: 'Trend trading',
    price: '$197 yearly',
    website: 'https://www.markettrendsignal.com/',
    winRate: undefined,
    averageReturn: undefined,
    holdingPeriod: undefined,
    score: undefined,
    risk: UNKNOWN,
    effort: undefined,
    reviewLink: '/reviews/hedgefund_z',
  },
  {
    key: 'Warrior Trading',
    status: COMPLETE,
    assetType: 'Stocks',
    strategy: 'Day trading',
    price: '$5,997 + $199 monthly',
    website: 'https://warriortrading.com',
    winRate: 0,
    averageReturn: -10,
    holdingPeriod: '10s',
    score: SCAM,
    risk: 'very high',
    effort: 'very high',
    reviewLink: '/reviews/warrior_trading',
  },
]

export default dataSource
